# Generated by Django 3.1.5 on 2021-04-05 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0005_order_orderitem_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pname",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="pid",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ordered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ordered_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="pname",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="pname",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="products.Product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default=None, max_length=5000, upload_to=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
