# Generated by Django 3.1.5 on 2021-04-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_cart_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
