# Generated by Django 3.1.5 on 2021-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_auto_20210407_0426"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
