# Generated by Django 3.1.5 on 2021-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_cart_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ManyToManyField(to="products.Cart"),
        ),
    ]
