# Generated by Django 3.1.5 on 2021-04-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_auto_20210408_0853"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.cart",
            ),
            preserve_default=False,
        ),
    ]
