# Generated by Django 3.1.5 on 2021-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_auto_20210408_0900"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ManyToManyField(to="products.Cart"),
        ),
    ]
