# Generated by Django 3.1.5 on 2021-04-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
