# Generated by Django 3.1.5 on 2021-04-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_auto_20210408_1445"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="products.Product"),
        ),
    ]
