# Generated by Django 3.1.5 on 2021-04-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_auto_20210409_0559"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total",
        ),
    ]
